/**
 * Configuração do schema do banco de dados Supabase.
 *
 * Schema atual da tabela:
 *
 *   CREATE TABLE public."TemperatureRegister" (
 *     id         bigint generated by default as identity PRIMARY KEY,
 *     created_at timestamptz NOT NULL DEFAULT now(),
 *     value      real
 *   );
 */

export const DB_CONFIG = {
  /** Nome da tabela no Supabase */
  table: "TemperatureRegister",

  /** Mapeamento: campo interno → nome real da coluna na tabela */
  columns: {
    id: "id",
    timestamp: "created_at",
    temperature: "value",
    /** Umidade ainda não existe no banco — será simulada no front */
    humidity: null as null,
    /** Coluna opcional de identificação do controlador. Deixe null se não existir. */
    controller: null as string | null,
  },

  /** Quantos registros carregar ao iniciar */
  initialLimit: 100,
} as const
